name: Backend code formatting and tests

on: push

jobs:
  code-check:
    name: Backend code formatting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' 
      - name: Run gofmt
        run: test -z $(gofmt -l .)
        working-directory: bloggy
      - name: Run go test
        run: go test ./...
        working-directory: bloggy
      
