name: Backend code formatting and tests

on: push

jobs:
  code-check:
    name: Backend code formatting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' 
      - name: Run gofmt
        run: test -z $(gofmt -l .)
        working-directory: bloggy
      - name: Start test services
        run: docker-compose -f test_services.yml up -d
        working-directory: bloggy
      - name: Wait for test services to be healthy
        timeout-minutes: 10
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Health.Status}} $cid`" != "healthy" ]; do 
              sleep 2; 
            done
          done
      - name: Run go test
        run: go test ./...
        working-directory: bloggy
      - name: Stop test services
        run: docker-compose -f test_services.yml down
        working-directory: bloggy
